### ISSUE TITLE
Discrepancy with `String::to_lowercase()

### ISSUE THREAD

**Issue by eeeebbbbrrrr** [RReverser/cow-utils-rs#2]
```rust
use cow_utils::*;

fn main() {
    let s = "ᾈ";
    assert_eq!(s.to_lowercase(), s.cow_to_lowercase())
}
```

```
$ cargo run                 
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/cwl`
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"ᾀ"`,
 right: `"ᾈ"`', src/main.rs:5:5
```

We ran across this doing some proptesting against some of our code that uses `cow_to_lowercase()`.  `ᾈ` has no particular meaning to us -- it's just the reduced value that `proptest` found.

I see this crate hasn't been updated in about 4 years, but I thought this was useful to report.  We really like `cow-utils`, so even if this is deemed unworthy of fixing, thanks for a great piece of software.

**Comment by thomcc** [comment]
This is wrong: https://github.com/RReverser/cow-utils-rs/blob/150e4c323ad775eaae0ca8a1cee74c4038985e45/src/lib.rs#L180 You're checking the `Lowercase` unicode property when you should be looking at `Changes_When_Uppercased`.

**Comment by thomcc** [comment]
The easy fix for this is probably to check `|c| c.to_lowercase() != c` rather than `char::is_uppercase`.

**Comment by RReverser** [comment]
Huh TIL. Unicode never ceases to surprise. That's pretty unfortunate - PRs certainly welcome!
